parameters:
#    ahs_blog.example.class: Ahs\BlogBundle\Example

services:
#    ahs_blog.example:
#        class: %ahs_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
